const admindata = [
    {
        fullname: "Jenny Wilson",
        email: "jennywilson123@gmail.com",
        contact: "+91 123 456 7890",
        role: "Role Management",
        status: "Active",
        users: "20",
    },
    {
        fullname: "Jacob Jones",
        email: "jacobjones223@gmail.com",
        contact: "+91 123 456 7890",
        role: "Role Management",
        status: "Active",
        users: "30",
    },
    {
        fullname: "Courtney Henry",
        email: "Courtneyhenry933@gmail.com",
        contact: "+91 123 456 7890",
        role: "Role Management",
        status: "Active",
        users: "10",
    },
    {
        fullname: "Darrel Stewart",
        email: "darrelstewart873@gmail.com",
        contact: "+91 123 456 7890",
        role: "Role Management",
        status: "Active",
        users: "90",
    },
    {
        fullname: "Bessie Cooper",
        email: "bessiecooper096@gmail.com",
        contact: "+91 123 456 7890",
        role: "Role Management",
        status: "Active",
        users: "12",
    },
    {
        fullname: "Jane Cooper",
        email: "janecooper567@gmail.com",
        contact: "+91 123 456 7890",
        role: "Role Management",
        status: "Active",
        users: "91",
    },
    {
        fullname: "Jarome Bell",
        email: "jaromebell620@gmail.com",
        contact: "+91 123 456 7890",
        role: "Role Management",
        status: "Active",
        users: "45",
    },
    {
        fullname: "Ronald Richards",
        email: "ronaldrichards007@gmail.com",
        contact: "+91 123 456 7890",
        role: "Role Management",
        status: "Active",
        users: "23",
    },
    {
        fullname: "Jenny Wilson",
        email: "jennywilson654@gmail.com",
        contact: "+91 123 456 7890",
        role: "Role Management",
        status: "Active",
        users: "34",
    },
    {
        fullname: "Annette Black",
        email: "annetteblack419@gmail.com",
        contact: "+91 123 456 7890",
        role: "Role Management",
        status: "Active",
        users: "45",
    }
]
export default admindata